export const rhymingWords = [
  { word: "along", score: 3124, numSyllables: 2 },
  { word: "long", score: 2255, numSyllables: 1 },
  { word: "strong", score: 2148, numSyllables: 1 },
  { word: "wrong", score: 1824, numSyllables: 1 },
  { word: "song", score: 1620, numSyllables: 1 },
  { word: "schlong", score: 1412, numSyllables: 1 },
  { word: "tang", score: 1122, numSyllables: 1 },
  { word: "throng", score: 1074, numSyllables: 1 },
  { word: "lifelong", score: 985, numSyllables: 2 },
  { word: "belong", score: 928, numSyllables: 2 },
  { word: "thong", score: 821, numSyllables: 1 },
  { word: "prolong", score: 776, numSyllables: 2 },
  { word: "bong", score: 770, numSyllables: 1 },
  { word: "twang", score: 762, numSyllables: 1 },
  { word: "pong", score: 745, numSyllables: 1 },
  { word: "prong", score: 683, numSyllables: 1 },
  { word: "gong", score: 650, numSyllables: 1 },
  { word: "furlong", score: 559, numSyllables: 2 },
  { word: "headstrong", score: 552, numSyllables: 2 },
  { word: "tong", score: 541, numSyllables: 1 },
  { word: "kong", score: 530, numSyllables: 1 },
  { word: "headlong", score: 485, numSyllables: 2 },
  { word: "wong", score: 471, numSyllables: 1 },
  { word: "yearlong", score: 439, numSyllables: 2 },
  { word: "hmong", score: 424, numSyllables: 2 },
  { word: "get along", score: 392, numSyllables: 3 },
  { word: "sarong", score: 383, numSyllables: 2 },
  { word: "weeklong", score: 337, numSyllables: 2 },
  { word: "hong", score: 313, numSyllables: 1 },
  { word: "armstrong", score: 301, numSyllables: 2 },
  { word: "clong", score: 301, numSyllables: 1 },
  { word: "daylong", score: 301, numSyllables: 2 },
  { word: "fong", score: 301, numSyllables: 1 },
  { word: "come along", score: 298, numSyllables: 3 },
  { word: "ong", score: 291, numSyllables: 1 },
  { word: "plainsong", score: 264, numSyllables: 2 },
  { word: "birdsong", score: 254, numSyllables: 2 },
  { word: "mong", score: 226, numSyllables: 1 },
  { word: "vietcong", score: 222, numSyllables: 2 },
  { word: "cong", score: 217, numSyllables: 1 },
  { word: "flong", score: 211, numSyllables: 1 },
  { word: "go along", score: 211, numSyllables: 3 },
  { word: "swang", score: 200, numSyllables: 1 },
  { word: "jiang", score: 184, numSyllables: 2 },
  { word: "scuppernong", score: 182, numSyllables: 3 },
  { word: "jong", score: 178, numSyllables: 1 },
  { word: "spong", score: 178, numSyllables: 1 },
  { word: "torch song", score: 178, numSyllables: 2 },
  { word: "chong", score: 172, numSyllables: 1 },
  { word: "huang", score: 167, numSyllables: 1 },
  { word: "yong", score: 164, numSyllables: 1 },
  { word: "kang", score: 163, numSyllables: 1 },
  { word: "stong", score: 162, numSyllables: 1 },
  { word: "klong", score: 156, numSyllables: 1 },
  { word: "so long", score: 154, numSyllables: 2 },
  { word: "rong", score: 145, numSyllables: 1 },
  { word: "swan song", score: 144, numSyllables: 2 },
  { word: "tag along", score: 144, numSyllables: 3 },
  { word: "monthlong", score: 138, numSyllables: 2 },
  { word: "hourlong", score: 124, numSyllables: 2 },
  { word: "all along", score: 123, numSyllables: 3 },
  { word: "zhang", score: 120, numSyllables: 1 },
  { word: "dwang", score: 118, numSyllables: 1 },
  { word: "sprong", score: 110, numSyllables: 1 },
  { word: "guangdong", score: 98, numSyllables: 2 },
  { word: "kwang", score: 97, numSyllables: 1 },
  { word: "zedong", score: 96, numSyllables: 2 },
  { word: "before long", score: 93, numSyllables: 3 },
  { word: "hong kong", score: 89, numSyllables: 2 },
  { word: "quang", score: 86, numSyllables: 1 },
  { word: "go long", score: 80, numSyllables: 2 },
  { word: "go wrong", score: 80, numSyllables: 2 },
  { word: "theme song", score: 75, numSyllables: 2 },
  { word: "delong", score: 73, numSyllables: 2 },
  { word: "string along", score: 73, numSyllables: 3 },
  { word: "chuang", score: 72, numSyllables: 1 },
  { word: "play along", score: 70, numSyllables: 3 },
  { word: "truong", score: 67, numSyllables: 1 },
  { word: "hwang", score: 66, numSyllables: 1 },
  { word: "folk song", score: 62, numSyllables: 2 },
  { word: "xiong", score: 60, numSyllables: 1 },
  { word: "neil armstrong", score: 56, numSyllables: 3 },
  { word: "kwong", score: 55, numSyllables: 1 },
  { word: "vong", score: 55, numSyllables: 1 },
  { word: "sense of right and wrong", score: 52, numSyllables: 5 },
  { word: "mao zedong", score: 50, numSyllables: 3 },
  { word: "pull along", score: 47, numSyllables: 3 },
  { word: "cannonball along", score: 43, numSyllables: 5 },
  { word: "phuong", score: 43, numSyllables: 2 },
  { word: "belt along", score: 42, numSyllables: 3 },
  { word: "civil wrong", score: 39, numSyllables: 3 },
  { word: "rush along", score: 39, numSyllables: 3 },
  { word: "zhejiang", score: 39, numSyllables: 2 },
  { word: "bucket along", score: 38, numSyllables: 4 },
  { word: "run along", score: 38, numSyllables: 3 },
  { word: "all day long", score: 35, numSyllables: 3 },
  { word: "pudong", score: 35, numSyllables: 2 },
  { word: "rub along", score: 35, numSyllables: 3 },
  { word: "right along", score: 34, numSyllables: 3 },
  { word: "kyong", score: 33, numSyllables: 1 },
  { word: "pelt along", score: 33, numSyllables: 3 },
  { word: "for a song", score: 30, numSyllables: 3 },
  { word: "scrape along", score: 29, numSyllables: 3 },
  { word: "dejong", score: 26, numSyllables: 2 },
  { word: "zoom along", score: 25, numSyllables: 3 },
  { word: "work song", score: 24, numSyllables: 2 },
  { word: "banquet song", score: 23, numSyllables: 3 },
  { word: "nasal twang", score: 22, numSyllables: 3 },
  { word: "giang", score: 21, numSyllables: 1 },
  { word: "scratch along", score: 21, numSyllables: 3 },
  { word: "tai long", score: 21, numSyllables: 2 },
  { word: "luong", score: 20, numSyllables: 2 },
  { word: "egg foo yong", score: 19, numSyllables: 3 },
  { word: "maung", score: 19, numSyllables: 1 },
  { word: "hong-kong", score: 18, numSyllables: 2 },
  { word: "jolly along", score: 18, numSyllables: 4 },
  { word: "drinking song", score: 17, numSyllables: 3 },
  { word: "religious song", score: 17, numSyllables: 4 },
  { word: "vuong", score: 16, numSyllables: 2 },
  { word: "stretch along", score: 15, numSyllables: 3 },
  { word: "aung", score: 14, numSyllables: 1 },
  { word: "shove along", score: 14, numSyllables: 3 },
  { word: "travel along", score: 13, numSyllables: 4 },
  { word: "budlong", score: 12, numSyllables: 2 },
  { word: "juang", score: 6, numSyllables: 1 },
  { word: "dejonge", score: 3, numSyllables: 2 },
  { word: "not long", score: 3, numSyllables: 2 },
  { word: "ziyang", score: 3, numSyllables: 2 },
  { word: "a long", numSyllables: 2 },
  { word: "chamlong", numSyllables: 2 },
  { word: "chengxiang", numSyllables: 2 },
  { word: "chenxiang", numSyllables: 2 },
  { word: "cuong", numSyllables: 1 },
  { word: "dejongh", numSyllables: 2 },
  { word: "drepung", numSyllables: 2 },
  { word: "hissong", numSyllables: 2 },
  { word: "hussong", numSyllables: 2 },
  { word: "hysong", numSyllables: 2 },
  { word: "kahng", numSyllables: 1 },
  { word: "kyoung", numSyllables: 1 },
  { word: "see-kiong", numSyllables: 2 },
  { word: "shougang", numSyllables: 2 },
  { word: "ssangyong", numSyllables: 2 },
  { word: "xudong", numSyllables: 2 },
  { word: "xuedong", numSyllables: 2 },
  { word: "yongue", numSyllables: 1 },
  { word: "yuzong", numSyllables: 2 },
];
